theme: jekyll-theme-cayman
title: MetaTube
description: Metadata Tube Plugin for Jellyfin/Emby.

url: https://github.com/metatube-community/jellyfin-plugin-metatube
repo: https://github.com/metatube-community/jellyfin-plugin-metatube
download_url: https://github.com/metatube-community/jellyfin-plugin-metatube/releases
show_downloads: true

github:
  is_project_page: true
  repository_name: jellyfin-plugin-metatube
  repository_url: https://github.com/metatube-community/jellyfin-plugin-metatube
